### ISSUE TITLE
Register button of lost Document css is not working

### ISSUE THREAD

**Issue by kaustuvjung** [AllblackNecrosword/Traffic-Management-System-#10]
![image](https://github.com/AllblackNecrosword/Traffic-Management-System-/assets/104540531/bd1a9be2-87c6-4553-b380-db780f6d0e99)

**Comment by stressedundermoutainofcode** [comment]
Try opening it again or in incognito mode. It is working perfectly fine on mine.
If it still doesn't work you can copy the code from git and try again.

**Comment by rabiiiii18** [comment]
<img width="594" alt="image" src="https://github.com/AllblackNecrosword/Traffic-Management-System-/assets/101962379/91fd09f3-40b1-4dd8-ac8f-c97961f0c920">

**Comment by rabiiiii18** [comment]
solved

**Comment by kaustuvjung** [comment]
good work
