### ISSUE TITLE
Bold font in lost vehicle form

### ISSUE THREAD

**Issue by Koshish-Khadka** [AllblackNecrosword/Traffic-Management-System-#11]
![image](https://github.com/AllblackNecrosword/Traffic-Management-System-/assets/111890745/68b18390-109e-4e6f-9707-fead1eed2071)

**Comment by rabiiiii18** [comment]
<img width="505" alt="Screenshot 2023-05-15 112607" src="https://github.com/AllblackNecrosword/Traffic-Management-System-/assets/101962379/186182da-cc63-40c0-9ef6-58cfe6ce9adb">

**Comment by rabiiiii18** [comment]
solved
