### ISSUE TITLE
Login page Responsive 

### ISSUE THREAD

**Issue by AllblackNecrosword** [AllblackNecrosword/Traffic-Management-System-#3]
The login page is not Responsive so I request to the developers to work on it.
![image](https://user-images.githubusercontent.com/111890745/229337604-b45e8804-08f1-4438-9ae7-70f40ef0b2be.png)

**Comment by stressedundermoutainofcode** [comment]
@rabiiiii18 you should look into it right now if you can

**Comment by rabiiiii18** [comment]
issue solved
<img width="960" alt="Screenshot 2023-04-02 163216" src="https://user-images.githubusercontent.com/101962379/229348232-e9e1d7e8-a504-4f04-9e2a-dd17fd90e96c.png">

**Comment by rabiiiii18** [comment]
![Uploading Screenshot 2023-05-15 112954.png…]()

**Comment by rabiiiii18** [comment]
the final looks
