### ISSUE TITLE
while registering vehicle error occured

### ISSUE THREAD

**Issue by kaustuvjung** [AllblackNecrosword/Traffic-Management-System-#9]
![image](https://github.com/AllblackNecrosword/Traffic-Management-System-/assets/104540531/449e258a-008b-434e-b681-57fbb7a6aa4f)

**Comment by stressedundermoutainofcode** [comment]
I'm sorry for the mistake. The table the data should be registered was changed by me to 'vehicleregestration' to 'regestration', I have updated the query it should work now.

**Comment by rabiiiii18** [comment]
it already solved
